export const CHALLENGES = [
  {
    id: "sequence",
    short: "Order",
    title: "Order matters",
    concept: "Sequence",
    prompt: "Build the exact route. The same commands in a different order can end somewhere else.",
    learn: "An algorithm is an ordered set of steps. Order changes behaviour.",
    kind: "builder",
    start: { x: 0, y: 4, direction: "E" }, goal: { x: 2, y: 3 },
    pool: ["MOVE", "MOVE", "LEFT", "MOVE"], slots: 4,
    solution: ["MOVE", "MOVE", "LEFT", "MOVE"],
  },
  {
    id: "trace",
    short: "Trace",
    title: "Think before Run",
    concept: "Tracing state",
    prompt: "Do not run yet. Read the program and tap the tile where Maro will finish.",
    learn: "Tracing means following state changes in your head before execution. Prediction makes debugging easier.",
    kind: "prediction",
    start: { x: 2, y: 4, direction: "N" },
    fixed: ["MOVE", "LEFT", "MOVE", "MOVE", "RIGHT", "MOVE"],
    answer: { x: 0, y: 2 },
  },
  {
    id: "debug",
    short: "Debug",
    title: "One bad instruction",
    concept: "Debugging",
    prompt: "One command is wrong. Select it, replace it, then test the repaired program.",
    learn: "Debugging is not guessing randomly: compare intended behaviour with actual behaviour, then change the smallest cause.",
    kind: "debug",
    start: { x: 0, y: 4, direction: "N" }, goal: { x: 3, y: 2 },
    fixed: ["MOVE", "MOVE", "LEFT", "MOVE", "MOVE", "MOVE"],
    correct: ["MOVE", "MOVE", "RIGHT", "MOVE", "MOVE", "MOVE"],
    wrongIndex: 2,
  },
  {
    id: "loop",
    short: "Loop",
    title: "Say it smaller",
    concept: "Loop / repetition",
    prompt: "Make a square without writing all eight actions. Choose the two-step pattern and the repeat count.",
    learn: "A loop expresses a repeated pattern once, then reuses it. Good algorithms remove needless repetition.",
    kind: "loop",
    start: { x: 1, y: 1, direction: "E" },
  },
  {
    id: "parameter",
    short: "Value",
    title: "One command, different distance",
    concept: "Parameters",
    prompt: "Set the two MOVE values so Maro reaches the beacon using only three blocks.",
    learn: "A parameter changes what a command does without inventing a new command. MOVE 1 and MOVE 4 share the same idea with different values.",
    kind: "parameter",
    start: { x: 0, y: 4, direction: "E" }, goal: { x: 4, y: 2 },
  },
  {
    id: "conditional",
    short: "If",
    title: "Make the program react",
    concept: "Conditionals",
    prompt: "Maro does not know exactly where the wall is. Choose a rule that reacts to what is ahead.",
    learn: "A conditional chooses an action from the current situation. This makes programs respond instead of only replaying fixed steps.",
    kind: "conditional",
    start: { x: 0, y: 2, direction: "E" }, goal: { x: 2, y: 4 }, walls: [[3,2],[3,3]],
  },
  {
    id: "colors",
    short: "Colors",
    title: "Follow the Colors",
    concept: "Conditions + movement",
    prompt: "Give each color its rule, then let Maro observe the tiles and react on the way to the workshop.",
    learn: "A condition lets a program observe what is happening and choose the next action. The same loop can react differently to each color.",
    kind: "colors",
    start: { x: 0, y: 4, direction: "E" }, goal: { x: 4, y: 0 },
    colors: { "0,4": "red", "0,3": "yellow", "0,0": "blue", "1,0": "yellow" },
  },
  {
    id: "lantern-patrol",
    short: "Patrol",
    title: "Lantern Patrol",
    concept: "Repeat until",
    prompt: "Choose the loop that keeps Maro moving, lights every lantern, and stops at the workshop.",
    learn: "REPEAT UNTIL describes the stopping condition, so the route length does not need to be entered manually.",
    kind: "patrol",
    start: { x: 0, y: 2, direction: "E" }, goal: { x: 4, y: 2 },
    lanterns: [[1,2], [2,2], [3,2]],
  },
  {
    id: "repair-patrol",
    short: "Repair",
    title: "Repair the Patrol Program",
    concept: "Debugging groups",
    prompt: "The patrol is stuck. Move one instruction out of the condition so Maro can reach every lantern.",
    learn: "Indentation groups instructions. When MOVE was inside IF, Maro could only move while already standing on a lantern.",
    kind: "repair-patrol",
    start: { x: 0, y: 2, direction: "E" }, goal: { x: 4, y: 2 },
    lanterns: [[1,2], [2,2], [3,2]],
  },
  {
    id: "mission-builder",
    short: "Create",
    title: "Build a Mission",
    concept: "Design a system",
    prompt: "Place Maro, a workshop, at least two lanterns, and optional walls. Build a program, explain your rule, then test your mission.",
    learn: "You designed the world and the algorithm together. Programming becomes an object to build, test, explain, and improve.",
    kind: "mission-builder",
    start: { x: 0, y: 4, direction: "E" }, goal: { x: 4, y: 0 },
    lanterns: [[2,4], [4,2]], walls: [],
  },
];
