export const CHALLENGES = [
  {
    id: "sequence",
    short: "Order",
    title: "Order matters",
    concept: "Sequence",
    prompt: "Build the exact route. The same commands in a different order can end somewhere else.",
    learn: "An algorithm is an ordered set of steps. Order changes behaviour.",
    kind: "builder",
    start: { x: 0, y: 4, direction: "E" }, goal: { x: 2, y: 3 },
    pool: ["MOVE", "MOVE", "LEFT", "MOVE"], slots: 4,
    solution: ["MOVE", "MOVE", "LEFT", "MOVE"],
  },
  {
    id: "trace",
    short: "Trace",
    title: "Think before Run",
    concept: "Tracing state",
    prompt: "Do not run yet. Read the program and tap the tile where Maro will finish.",
    learn: "Tracing means following state changes in your head before execution. Prediction makes debugging easier.",
    kind: "prediction",
    start: { x: 2, y: 4, direction: "N" },
    fixed: ["MOVE", "LEFT", "MOVE", "MOVE", "RIGHT", "MOVE"],
    answer: { x: 0, y: 2 },
  },
  {
    id: "debug",
    short: "Debug",
    title: "One bad instruction",
    concept: "Debugging",
    prompt: "One command is wrong. Select it, replace it, then test the repaired program.",
    learn: "Debugging is not guessing randomly: compare intended behaviour with actual behaviour, then change the smallest cause.",
    kind: "debug",
    start: { x: 0, y: 4, direction: "N" }, goal: { x: 3, y: 2 },
    fixed: ["MOVE", "MOVE", "LEFT", "MOVE", "MOVE", "MOVE"],
    correct: ["MOVE", "MOVE", "RIGHT", "MOVE", "MOVE", "MOVE"],
    wrongIndex: 2,
  },
  {
    id: "loop",
    short: "Loop",
    title: "Say it smaller",
    concept: "Loop / repetition",
    prompt: "Make a square without writing all eight actions. Choose the two-step pattern and the repeat count.",
    learn: "A loop expresses a repeated pattern once, then reuses it. Good algorithms remove needless repetition.",
    kind: "loop",
    start: { x: 1, y: 1, direction: "E" },
  },
  {
    id: "parameter",
    short: "Value",
    title: "One command, different distance",
    concept: "Parameters",
    prompt: "Set the two MOVE values so Maro reaches the beacon using only three blocks.",
    learn: "A parameter changes what a command does without inventing a new command. MOVE 1 and MOVE 4 share the same idea with different values.",
    kind: "parameter",
    start: { x: 0, y: 4, direction: "E" }, goal: { x: 4, y: 2 },
  },
  {
    id: "conditional",
    short: "If",
    title: "Make the program react",
    concept: "Conditionals",
    prompt: "Maro does not know exactly where the wall is. Choose a rule that reacts to what is ahead.",
    learn: "A conditional chooses an action from the current situation. This makes programs respond instead of only replaying fixed steps.",
    kind: "conditional",
    start: { x: 0, y: 2, direction: "E" }, goal: { x: 2, y: 4 }, walls: [[3,2],[3,3]],
  },
  {
    id: "variable",
    short: "Store",
    title: "Remember a value",
    concept: "Variables",
    prompt: "The distance changes between tests. Choose the program that still works without rewriting its number.",
    learn: "A variable gives a name to a value. When the value changes, instructions using the name can adapt automatically.",
    kind: "variable",
  },
  {
    id: "function",
    short: "Reuse",
    title: "Teach Maro a shortcut",
    concept: "Functions / procedures",
    prompt: "A corner manoeuvre appears twice. Build it once as CORNER(), then reuse the new command.",
    learn: "A function packages a useful mini-algorithm behind a name. Reuse makes larger programs easier to understand and change.",
    kind: "function",
    start: { x: 0, y: 4, direction: "E" }, goal: { x: 0, y: 2 },
  },
  {
    id: "efficiency",
    short: "Better",
    title: "Same result, less work",
    concept: "Efficiency",
    prompt: "All three programs claim to solve the same task. Test them and choose the clearest valid program with the fewest written blocks.",
    learn: "Algorithms can be compared, not only marked correct or wrong. Simpler or more efficient solutions can be easier to maintain and reason about.",
    kind: "efficiency",
    start: { x: 1, y: 1, direction: "E" }, goal: { x: 1, y: 1 },
  },
  {
    id: "generalize",
    short: "Smart",
    title: "One program, three mazes",
    concept: "Generalization",
    prompt: "A hard-coded route works on one map. Choose an algorithm that can react and solve all three test maps.",
    learn: "A stronger algorithm captures a rule that works across cases, not just one memorized answer. That is a step from instructions toward problem solving.",
    kind: "generalize",
  },
];
